export const REPORT_DOCUMENT_V1_BUILD = false;
export const REPORT_DOCUMENT_V1_DESIGNER = false;
export const PAGE_PLAN_V1_SAVE = false;
export const REPORT_DOCUMENT_V1_SHADOW_COMPARE = false;
export const OFFICIAL_PDF_V1 = false;
export const OFFICIAL_WORD_V1 = false;
export const REPORT_DOCUMENT_V1_STRICT_VALIDATION = false;
export const LEGACY_REPORT_EXPORT_FALLBACK = false;

export const REPORT_DOCUMENT_V1_FEATURE_FLAGS = Object.freeze({
  REPORT_DOCUMENT_V1_BUILD,
  REPORT_DOCUMENT_V1_DESIGNER,
  PAGE_PLAN_V1_SAVE,
  REPORT_DOCUMENT_V1_SHADOW_COMPARE,
  OFFICIAL_PDF_V1,
  OFFICIAL_WORD_V1,
  REPORT_DOCUMENT_V1_STRICT_VALIDATION,
  LEGACY_REPORT_EXPORT_FALLBACK,
});

export type ReportDocumentV1FeatureFlagName = keyof typeof REPORT_DOCUMENT_V1_FEATURE_FLAGS;
